#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom admiral compute_bmi
#' @importFrom admiral convert_blanks_to_na
#' @importFrom anthro anthro_zscores
#' @importFrom dplyr across
#' @importFrom dplyr any_of
#' @importFrom dplyr arrange
#' @importFrom dplyr contains
#' @importFrom dplyr count
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_minimal
#' @importFrom janitor clean_names
#' @importFrom janitor remove_empty
#' @importFrom lubridate month
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @importFrom rlang warn
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_flatten
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_to_upper
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr tibble
#' @importFrom tidyr unite
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect everything
#' @importFrom tidyselect starts_with
## usethis namespace: end
NULL
